version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: okare
      POSTGRES_USER: okare
      POSTGRES_PASSWORD: okarepassword
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./core
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/okare
      SPRING_DATASOURCE_USERNAME: okare
      SPRING_DATASOURCE_PASSWORD: okarepassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      # Add other env vars as needed
    depends_on:
      - db
    ports:
      - '8080:8080'

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8080
      # Add other env vars as needed
    depends_on:
      - backend
    ports:
      - '3000:3000'

volumes:
  db_data:
