/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/user/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user's profile
         * @description Retrieves the profile of the authenticated user based on the current session.
         */
        get: operations["getCurrentUser"];
        /**
         * Update current user's profile
         * @description Updates the profile of the authenticated user based on the provided data.
         */
        put: operations["updateUserProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisation/{organisationId}/member/role/{role}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateMemberRole"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisation/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateOrganisation"];
        post: operations["createOrganisation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/item/{lineItemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a line item by ID
         * @description Retrieves a specific line item by its ID, if the user has access.
         */
        get: operations["getLineItemById"];
        /**
         * Update an existing line item
         * @description Updates a line item with the specified ID, if the user has access.
         */
        put: operations["updateLineItem"];
        post?: never;
        /**
         * Delete a line item by ID
         * @description Deletes a line item with the specified ID, if the user has access.
         */
        delete: operations["deleteLineItemById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an invoice by ID
         * @description Retrieves a specific invoice by its ID, if the user has access.
         */
        get: operations["getInvoiceById"];
        /**
         * Update an existing invoice
         * @description Updates an invoice with the specified ID, if the user has access.
         */
        put: operations["updateInvoice"];
        post?: never;
        /**
         * Delete an invoice
         * @description Deletes an invoice with the specified ID, if the user has access and the invoice is not paid or cancelled.
         */
        delete: operations["deleteInvoice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/{clientId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a client by ID
         * @description Retrieves a specific client by its ID, if the user has access.
         */
        get: operations["getClientById"];
        /**
         * Update an existing client
         * @description Updates a client with the specified ID, if the user has access.
         */
        put: operations["updateClient"];
        post?: never;
        /**
         * Delete a client by ID
         * @description Deletes a client with the specified ID, if the user has access.
         */
        delete: operations["deleteClientById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/{clientId}/archive/{status}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Updates the archival status of a client
         * @description Archives or unarchives a client based on the provided status, if the user has access.
         */
        put: operations["updateArchiveStatusByClientId"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/block/schema/{blockTypeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update an existing block type
         * @description Updates a block type with the specified ID. Does not allow changing the scope of the block type.
         */
        put: operations["updateBlockType"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/block/schema/{blockTypeId}/archive/{status}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Archive a block type
         * @description Archives a block type by its ID. The block type will still be visible to users currently using it but cannot be used in new blocks.
         */
        put: operations["updateArchiveStatusByBlockTypeId"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisation/invite/reject/{inviteToken}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rejectInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisation/invite/organisation/{organisationId}/email/{email}/role/{role}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["inviteToOrganisation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisation/invite/accept/{inviteToken}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["acceptInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/item/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new line item
         * @description Creates a new line item based on the provided request data.
         */
        post: operations["createLineItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel an invoice
         * @description Cancels an invoice with the specified ID, if the user has access and the invoice is not paid or already cancelled.
         */
        post: operations["cancelInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all invoices for them provided organisation
         * @description Retrieves a list of invoices associated with the provided organisation
         */
        get: operations["getUserInvoices"];
        put?: never;
        /**
         * Create a new invoice
         * @description Creates a new invoice based on the provided request data.
         */
        post: operations["createInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new client
         * @description Creates a new client based on the provided request data.
         */
        post: operations["createClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/block/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new block type
         * @description Creates and publishes a new block type based on the provided request data.
         */
        post: operations["publishBlockType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/block/environment/overwrite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Overwrite Block Environment
         * @description Overwrites the entire block environment with the provided data.
         */
        post: operations["overwriteBlockEnvironment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/block/environment/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Block Environment
         * @description Saves the block environment including layout and structural operations.
         */
        post: operations["saveBlockEnvironment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a user by ID
         * @description Retrieves a specific user's profile by their ID, if the user has access.
         */
        get: operations["getUserById"];
        put?: never;
        post?: never;
        /**
         * Delete a user profile by ID
         * @description Deletes a user profile with the specified ID, if the user has access.
         */
        delete: operations["deleteUserProfileById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisation/{organisationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOrganisation"];
        put?: never;
        post?: never;
        delete: operations["deleteOrganisation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisation/invite/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserInvites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisation/invite/organisation/{organisationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOrganisationInvites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/item/organisation/{organisationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all line items for an organisation
         * @description Retrieves a list of line items associated with a given organisation.
         */
        get: operations["getLineItemsForOrganisation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{id}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Generate invoice document
         * @description Generates a PDF document for the invoice with the specified ID, if the user has access.
         */
        get: operations["generateInvoiceDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/client": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get invoices for a specific client
         * @description Retrieves a list of invoices for the specified client, if the user has access.
         */
        get: operations["getClientInvoices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/organisation/{organisationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all clients for the organisation
         * @description Retrieves a list of clients for a given organisation. Given the user is authenticated, and belongs to that specified organisation
         */
        get: operations["getOrganisationClients"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/block/schema/organisation/{organisationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get block types for organisation
         * @description Retrieves all block types associated with a specific organisation.
         */
        get: operations["getBlockTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/block/schema/key/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get block type by key
         * @description Retrieves a block type by its unique key.
         */
        get: operations["getBlockTypeByKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/block/environment/organisation/{organisationId}/type/{type}/id/{entityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Block Environment
         * @description Retrieves the block environment for the specified entity. Creates a default layout if none exists (lazy initialization).
         */
        get: operations["getBlockEnvironment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisation/{organisationId}/member": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeMemberFromOrganisation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisation/invite/organisation/{organisationId}/invitation/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeInvite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Address: {
            street: string;
            city: string;
            state: string;
            postalCode: string;
            country: string;
        };
        MembershipDetails: {
            organisation?: components["schemas"]["Organisation"];
            /** @enum {string} */
            role: "OWNER" | "ADMIN" | "MEMBER";
            /** Format: date-time */
            memberSince: string;
        };
        Organisation: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "organisation";
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            plan: "FREE" | "STARTUP" | "SCALE" | "ENTERPRISE";
            defaultCurrency: {
                currencyCode?: string;
                /** Format: int32 */
                numericCode?: number;
                numericCodeAsString?: string;
                displayName?: string;
                symbol?: string;
                /** Format: int32 */
                defaultFractionDigits?: number;
            };
            avatarUrl?: string;
            businessNumber?: string;
            taxId?: string;
            address?: components["schemas"]["Address"];
            organisationPaymentDetails?: components["schemas"]["OrganisationPaymentDetails"];
            /** Format: int32 */
            memberCount: number;
            /** Format: date-time */
            createdAt?: string;
            members: components["schemas"]["OrganisationMember"][];
            invites: components["schemas"]["OrganisationInvite"][];
        };
        OrganisationInvite: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organisationId: string;
            email: string;
            inviteToken: string;
            /** Format: uuid */
            invitedBy?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
            /** @enum {string} */
            role: "OWNER" | "ADMIN" | "MEMBER";
            /** @enum {string} */
            status: "PENDING" | "ACCEPTED" | "DECLINED" | "EXPIRED";
        };
        OrganisationMember: {
            user: components["schemas"]["UserDisplay"];
            membershipDetails: components["schemas"]["MembershipDetails"];
        };
        OrganisationPaymentDetails: {
            bsb?: string;
            accountNumber?: string;
            accountName?: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            email: string;
            name: string;
            phone?: string;
            avatarUrl?: string;
            memberships: components["schemas"]["MembershipDetails"][];
            defaultOrganisation?: components["schemas"]["Organisation"];
        };
        UserDisplay: {
            /** Format: uuid */
            id: string;
            email: string;
            name: string;
            avatarUrl?: string;
        };
        LineItem: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            organisationId: string;
            description?: string;
            /** @enum {string} */
            type: "SERVICE" | "PRODUCT" | "FEE" | "DISCOUNT";
            chargeRate: number;
        };
        Billable: {
            /** Format: date-time */
            date: string;
            description: string;
            lineItem: components["schemas"]["LineItem"];
            /** @enum {string} */
            billableType: "HOURS" | "DISTANCE" | "QUANTITY" | "FIXED";
            quantity: number;
        };
        Client: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "client";
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organisationId: string;
            name: string;
            contact: components["schemas"]["Contact"];
            /** @enum {string} */
            clientType?: "PROSPECT" | "CUSTOMER" | "SUBSCRIBER" | "SERVICE" | "ENTERPRISE" | "PARTNER" | "VENDOR" | "DORMANT" | "TRIAL" | "CHURNED" | "INFLUENCER" | "OTHER";
            company?: components["schemas"]["Company"];
            role?: string;
            archived: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: uuid */
            createdBy?: string;
            /** Format: uuid */
            updatedBy?: string;
        };
        Company: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organisationId: string;
            name: string;
            address?: components["schemas"]["Address"];
            phone?: string;
            email?: string;
            website?: string;
            businessNumber?: string;
            logoUrl?: string;
            archived: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: uuid */
            createdBy?: string;
            /** Format: uuid */
            updatedBy?: string;
        };
        Contact: {
            email: string;
            phone?: string;
            address?: components["schemas"]["Address"];
            additionalContacts?: {
                [key: string]: string;
            };
        };
        Invoice: {
            /** Format: uuid */
            id: string;
            organisation: components["schemas"]["Organisation"];
            client: components["schemas"]["Client"];
            template?: components["schemas"]["TemplateInvoiceTemplateFieldStructure"];
            reportTemplate?: components["schemas"]["TemplateReportTemplateFieldStructure"];
            invoiceNumber: string;
            items: components["schemas"]["Billable"][];
            amount: number;
            currency: {
                currencyCode?: string;
                /** Format: int32 */
                numericCode?: number;
                numericCodeAsString?: string;
                displayName?: string;
                symbol?: string;
                /** Format: int32 */
                defaultFractionDigits?: number;
            };
            /** @enum {string} */
            status: "PENDING" | "PAID" | "OVERDUE" | "OUTDATED" | "CANCELLED";
            dates: components["schemas"]["InvoiceDates"];
            customFields: {
                [key: string]: Record<string, never>;
            };
        };
        InvoiceDates: {
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            /** Format: date-time */
            issueDate: string;
            /** Format: date-time */
            dueDate?: string;
            /** Format: date-time */
            invoiceCreatedAt?: string;
            /** Format: date-time */
            invoiceUpdatedAt?: string;
        };
        InvoiceTemplateFieldStructure: {
            name: string;
            description?: string;
            type: string;
            required: boolean;
            children: components["schemas"]["InvoiceTemplateFieldStructure"][];
        };
        ReportTemplateFieldStructure: {
            name: string;
            description?: string;
            type: string;
            required: boolean;
            children: components["schemas"]["ReportTemplateFieldStructure"][];
        };
        TemplateInvoiceTemplateFieldStructure: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId?: string;
            name: string;
            description?: string;
            /** @enum {string} */
            type: "CLIENT" | "INVOICE" | "REPORT";
            structure: {
                [key: string]: components["schemas"]["InvoiceTemplateFieldStructure"];
            };
            isDefault: boolean;
            isPremade: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        TemplateReportTemplateFieldStructure: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId?: string;
            name: string;
            description?: string;
            /** @enum {string} */
            type: "CLIENT" | "INVOICE" | "REPORT";
            structure: {
                [key: string]: components["schemas"]["ReportTemplateFieldStructure"];
            };
            isDefault: boolean;
            isPremade: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        BindingSource: {
            type: string;
        };
        BlockBinding: {
            prop: string;
            source: components["schemas"]["Computed"] | components["schemas"]["DataPath"];
        };
        BlockComponentNode: {
            id: string;
            /** @enum {string} */
            type: "LAYOUT_CONTAINER" | "LIST" | "CONTACT_CARD" | "ADDRESS_CARD" | "LINE_ITEM" | "TABLE" | "IMAGE" | "BUTTON" | "ATTACHMENT" | "TEXT" | "FALLBACK";
            props: {
                [key: string]: unknown;
            };
            bindings: components["schemas"]["BlockBinding"][];
            slots?: {
                [key: string]: string[];
            };
            slotLayout?: {
                [key: string]: components["schemas"]["LayoutGrid"];
            };
            widgetMeta?: {
                [key: string]: Record<string, never>;
            };
            visible?: components["schemas"]["Condition"];
            /** @enum {string} */
            fetchPolicy: "INHERIT" | "LAZY" | "EAGER";
        };
        BlockDisplay: {
            form: components["schemas"]["BlockFormStructure"];
            render: components["schemas"]["BlockRenderStructure"];
        };
        BlockFormStructure: {
            fields: {
                [key: string]: components["schemas"]["FormWidgetConfig"];
            };
        };
        BlockRenderStructure: {
            /** Format: int32 */
            version: number;
            layoutGrid: components["schemas"]["LayoutGrid"];
            components: {
                [key: string]: components["schemas"]["BlockComponentNode"];
            };
            theme?: components["schemas"]["ThemeTokens"];
        };
        BlockSchema: {
            name: string;
            description?: string;
            /** @enum {string} */
            type: "STRING" | "NUMBER" | "BOOLEAN" | "OBJECT" | "ARRAY" | "NULL";
            /** @enum {string} */
            format?: "DATE" | "DATETIME" | "EMAIL" | "PHONE" | "CURRENCY" | "URL" | "PERCENTAGE";
            required: boolean;
            properties?: {
                [key: string]: components["schemas"]["BlockSchema"];
            };
            items?: components["schemas"]["BlockSchema"];
        };
        BlockType: {
            /** Format: uuid */
            id: string;
            key: string;
            /** Format: int32 */
            version: number;
            name: string;
            /** Format: uuid */
            sourceId?: string;
            nesting?: components["schemas"]["BlockTypeNesting"];
            description?: string;
            /** Format: uuid */
            organisationId?: string;
            archived: boolean;
            /** @enum {string} */
            strictness: "SOFT" | "STRICT" | "NONE";
            system: boolean;
            schema: components["schemas"]["BlockSchema"];
            display: components["schemas"]["BlockDisplay"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: uuid */
            createdBy?: string;
            /** Format: uuid */
            updatedBy?: string;
        };
        BlockTypeNesting: {
            /** Format: int32 */
            max?: number;
            allowedTypes: string[];
        };
        Computed: {
            type: "Computed";
        } & (Omit<components["schemas"]["BindingSource"], "type"> & {
            expr: string;
            engine: string;
        });
        Condition: {
            /** @enum {string} */
            op: "EXISTS" | "EQUALS" | "NOT_EQUALS" | "GT" | "GTE" | "LT" | "LTE" | "IN" | "NOT_IN" | "EMPTY" | "NOT_EMPTY";
            left: components["schemas"]["Path"] | components["schemas"]["Value"];
            right?: components["schemas"]["Path"] | components["schemas"]["Value"];
        };
        DataPath: {
            type: "DataPath";
        } & (Omit<components["schemas"]["BindingSource"], "type"> & {
            path: string;
        });
        FormWidgetConfig: {
            /** @enum {string} */
            type: "TEXT_INPUT" | "NUMBER_INPUT" | "CHECKBOX" | "RADIO_BUTTON" | "DROPDOWN" | "DATE_PICKER" | "EMAIL_INPUT" | "PHONE_INPUT" | "CURRENCY_INPUT" | "TEXT_AREA" | "FILE_UPLOAD" | "SLIDER" | "TOGGLE_SWITCH";
            label: string;
            description?: string;
            tooltip?: string;
            placeholder?: string;
            options?: components["schemas"]["Option"][];
        };
        GridRect: {
            /** Format: int32 */
            x: number;
            /** Format: int32 */
            y: number;
            /** Format: int32 */
            margin?: number;
            /** Format: int32 */
            width: number;
            /** Format: int32 */
            height: number;
            locked: boolean;
        };
        LayoutGrid: {
            layout: components["schemas"]["GridRect"];
            items: components["schemas"]["LayoutGridItem"][];
        };
        LayoutGridItem: {
            id: string;
            rect: components["schemas"]["GridRect"];
        };
        Operand: {
            kind: string;
        };
        Option: {
            label: string;
            value: string;
        };
        Path: {
            kind: "Path";
        } & (Omit<components["schemas"]["Operand"], "kind"> & {
            path: string;
        });
        ThemeTokens: {
            variant?: string;
            colorRole?: string;
            tone?: string;
        };
        Value: {
            kind: "Value";
        } & (Omit<components["schemas"]["Operand"], "kind"> & {
            value?: Record<string, never>;
        });
        OrganisationCreationRequest: {
            name: string;
            avatarUrl?: string;
            /** @enum {string} */
            plan: "FREE" | "STARTUP" | "SCALE" | "ENTERPRISE";
            defaultCurrency: string;
            isDefault: boolean;
            businessNumber?: string;
            taxId?: string;
            address: components["schemas"]["Address"];
            payment?: components["schemas"]["OrganisationPaymentDetails"];
            customAttributes: {
                [key: string]: Record<string, never>;
            };
        };
        LineItemCreationRequest: {
            name: string;
            /** Format: uuid */
            organisationId: string;
            description?: string;
            chargeRate: number;
        };
        InvoiceCreationRequest: {
            /** Format: uuid */
            clientId: string;
            /** Format: uuid */
            organisationId: string;
            template: components["schemas"]["TemplateInvoiceTemplateFieldStructure"];
            reportTemplate?: components["schemas"]["TemplateReportTemplateFieldStructure"];
            invoiceNumber: string;
            items: components["schemas"]["Billable"][];
            amount: number;
            currency: {
                currencyCode?: string;
                /** Format: int32 */
                numericCode?: number;
                numericCodeAsString?: string;
                displayName?: string;
                symbol?: string;
                /** Format: int32 */
                defaultFractionDigits?: number;
            };
            /** @enum {string} */
            status: "PENDING" | "PAID" | "OVERDUE" | "OUTDATED" | "CANCELLED";
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            /** Format: date-time */
            dueDate?: string;
            /** Format: date-time */
            issueDate: string;
            customFields: {
                [key: string]: Record<string, never>;
            };
        };
        ClientCreationRequest: {
            name: string;
            /** Format: uuid */
            organisationId: string;
            /** Format: uuid */
            companyId?: string;
            companyRole?: string;
            contact: components["schemas"]["Contact"];
        };
        CreateBlockTypeRequest: {
            key: string;
            name: string;
            description?: string;
            /** @enum {string} */
            mode: "SOFT" | "STRICT" | "NONE";
            schema: components["schemas"]["BlockSchema"];
            display: components["schemas"]["BlockDisplay"];
            /** Format: uuid */
            organisationId: string;
        };
        Block: {
            /** Format: uuid */
            id: string;
            name?: string;
            /** Format: uuid */
            organisationId: string;
            type: components["schemas"]["BlockType"];
            payload: components["schemas"]["EntityReferenceMetadata"] | components["schemas"]["BlockReferenceMetadata"] | components["schemas"]["BlockContentMetadata"];
            archived: boolean;
            validationErrors?: string[];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: uuid */
            createdBy?: string;
            /** Format: uuid */
            updatedBy?: string;
        };
        BlockContentMetadata: WithRequired<components["schemas"]["Metadata"], "deletable" | "meta" | "type"> & {
            data: {
                [key: string]: unknown;
            };
            listConfig?: components["schemas"]["BlockListConfiguration"];
        };
        BlockEnvironment: {
            layout: components["schemas"]["BlockTreeLayout"];
            trees: components["schemas"]["BlockTree"][];
        };
        BlockListConfiguration: {
            allowedTypes?: string[];
            allowDuplicates: boolean;
            display: components["schemas"]["ListDisplayConfig"];
            config: components["schemas"]["ListConfig"];
        };
        BlockMeta: {
            validationErrors: string[];
            computedFields?: {
                [key: string]: unknown;
            };
            /** Format: int32 */
            lastValidatedVersion?: number;
        };
        BlockReferenceMetadata: components["schemas"]["ReferenceMetadata"] & {
            /** Format: int32 */
            expandDepth: number;
            item: components["schemas"]["ReferenceItem"];
        };
        BlockTree: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "block_tree";
            root: components["schemas"]["ContentNode"] | components["schemas"]["ReferenceNode"];
        };
        BlockTreeLayout: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organisationId: string;
            layout: components["schemas"]["TreeLayout"];
            /** Format: int32 */
            version: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: uuid */
            createdBy?: string;
            /** Format: uuid */
            updatedBy?: string;
        };
        BlockTreeReference: WithRequired<components["schemas"]["ReferencePayload"], "type"> & {
            reference: components["schemas"]["Reference"];
        };
        BreakpointConfig: {
            /** Format: int32 */
            w: number;
            /** Format: int32 */
            c: number;
        };
        ColumnOptions: {
            breakpoints?: components["schemas"]["BreakpointConfig"][];
            layout?: string;
        };
        ContentNode: WithRequired<components["schemas"]["Node"], "block" | "type" | "warnings"> & {
            children?: components["schemas"]["Node"][];
        };
        DraggableOptions: {
            cancel?: string;
            /** Format: int32 */
            pause?: number;
            handle?: string;
            appendTo?: string;
            scroll?: boolean;
        };
        EntityReference: WithRequired<components["schemas"]["ReferencePayload"], "type"> & {
            reference: components["schemas"]["Reference"][];
        };
        EntityReferenceMetadata: components["schemas"]["ReferenceMetadata"] & {
            /** @enum {string} */
            presentation: "SUMMARY" | "ENTITY" | "TABLE" | "GRID" | "INLINE";
            items: components["schemas"]["ReferenceItem"][];
            projection: components["schemas"]["Projection"];
            allowedTypes?: ("line_item" | "client" | "company" | "invoice" | "block_tree" | "report" | "document" | "project" | "organisation" | "task" | "block_type" | "block" | "user")[];
            display: components["schemas"]["ListDisplayConfig"];
            config: components["schemas"]["ListConfig"];
            allowDuplicates: boolean;
        };
        FilterSpec: {
            expr: {
                [key: string]: unknown;
            };
        };
        ListConfig: {
            /** @enum {string} */
            mode: "MANUAL" | "SORTED";
            sort?: components["schemas"]["SortSpec"];
            filters: components["schemas"]["FilterSpec"][];
            /** @enum {string} */
            filterLogic: "AND" | "OR";
        };
        ListDisplayConfig: {
            /** Format: int32 */
            itemSpacing: number;
            showDragHandles: boolean;
            emptyMessage: string;
            paging?: components["schemas"]["PagingSpec"];
        };
        Metadata: {
            /** @enum {string} */
            type: "content" | "entity_reference" | "block_reference";
            meta: components["schemas"]["BlockMeta"];
            deletable: boolean;
        };
        Node: {
            warnings: string[];
            /** @enum {string} */
            type: "reference_node" | "content_node";
            block: components["schemas"]["Block"];
        };
        OverwriteEnvironmentRequest: {
            /** Format: uuid */
            layoutId: string;
            /** Format: uuid */
            organisationId: string;
            /** Format: int32 */
            version: number;
            environment: components["schemas"]["BlockEnvironment"];
        };
        PagingSpec: {
            /** Format: int32 */
            pageSize: number;
        };
        Projection: {
            fields: string[];
            /** Format: uuid */
            templateId?: string;
        };
        Reference: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            entityType: "line_item" | "client" | "company" | "invoice" | "block_tree" | "report" | "document" | "project" | "organisation" | "task" | "block_type" | "block" | "user";
            /** Format: uuid */
            entityId: string;
            path?: string;
            /** Format: int32 */
            orderIndex?: number;
            /** @description Inline, discriminated entity */
            entity?: components["schemas"]["Referenceable"];
            /** @enum {string} */
            warning?: "MISSING" | "REQUIRES_LOADING" | "UNSUPPORTED" | "CIRCULAR" | "DEPTH_EXCEEDED";
        };
        ReferenceItem: {
            /** @enum {string} */
            type: "line_item" | "client" | "company" | "invoice" | "block_tree" | "report" | "document" | "project" | "organisation" | "task" | "block_type" | "block" | "user";
            /** Format: uuid */
            id: string;
            labelOverride?: string;
            badge?: string;
        };
        ReferenceMetadata: WithRequired<components["schemas"]["Metadata"], "deletable" | "meta" | "type"> & {
            path: string;
            /** @enum {string} */
            fetchPolicy: "LAZY" | "EAGER";
        };
        ReferenceNode: WithRequired<components["schemas"]["Node"], "block" | "type" | "warnings"> & {
            reference: components["schemas"]["EntityReference"] | components["schemas"]["BlockTreeReference"];
        };
        ReferencePayload: {
            /** @enum {string} */
            type: "block_reference" | "entity_reference";
        };
        Referenceable: {
            /** @enum {string} */
            type: "line_item" | "client" | "company" | "invoice" | "block_tree" | "report" | "document" | "project" | "organisation" | "task" | "block_type" | "block" | "user";
        } & (components["schemas"]["Client"] | components["schemas"]["Organisation"] | components["schemas"]["BlockTree"]);
        RenderContent: {
            id: string;
            key: string;
            /** @enum {string} */
            renderType: "list" | "component" | "container";
            /** @enum {string} */
            blockType: "reference_node" | "content_node";
        };
        ResizableOptions: {
            handles?: string;
            autoHide?: boolean;
        };
        SortSpec: {
            by: string;
            /** @enum {string} */
            dir: "ASC" | "DESC";
        };
        TreeLayout: {
            resizable?: components["schemas"]["ResizableOptions"];
            draggable?: components["schemas"]["DraggableOptions"];
            /** Format: int32 */
            margin?: number;
            /** Format: int32 */
            marginTop?: number;
            /** Format: int32 */
            marginRight?: number;
            /** Format: int32 */
            marginBottom?: number;
            /** Format: int32 */
            marginLeft?: number;
            acceptWidgets?: boolean;
            alwaysShowResizeHandle?: boolean;
            animate?: boolean;
            auto?: boolean;
            /** Format: int32 */
            cellHeight?: number;
            /** Format: int32 */
            column?: number;
            columnOpts?: components["schemas"]["ColumnOptions"];
            disableDrag?: boolean;
            disableOneColumnMode?: boolean;
            disableResize?: boolean;
            float?: boolean;
            handle?: string;
            handleClass?: string;
            itemClass?: string;
            /** Format: int32 */
            maxRow?: number;
            /** Format: int32 */
            minRow?: number;
            /** Format: int32 */
            oneColumnSize?: number;
            placeholderClass?: string;
            placeholderText?: string;
            removable?: boolean;
            /** Format: int32 */
            removeTimeout?: number;
            /** Format: int32 */
            row?: number;
            rtl?: boolean;
            staticGrid?: boolean;
            styleInHead?: boolean;
            layout?: string;
            class?: string;
            children?: components["schemas"]["Widget"][];
        };
        Widget: {
            id: string;
            /** Format: int32 */
            x: number;
            /** Format: int32 */
            y: number;
            /** Format: int32 */
            w: number;
            /** Format: int32 */
            h: number;
            /** Format: int32 */
            minW?: number;
            /** Format: int32 */
            minH?: number;
            /** Format: int32 */
            maxW?: number;
            /** Format: int32 */
            maxH?: number;
            autoPosition?: boolean;
            locked?: boolean;
            noResize?: boolean;
            noMove?: boolean;
            content?: components["schemas"]["RenderContent"];
            subGridOpts?: components["schemas"]["TreeLayout"];
        };
        OverwriteEnvironmentResponse: {
            success: boolean;
            environment: components["schemas"]["BlockEnvironment"];
        };
        AddBlockOperation: WithRequired<components["schemas"]["BlockOperation"], "blockId" | "type"> & {
            block: components["schemas"]["ContentNode"] | components["schemas"]["ReferenceNode"];
            /** Format: uuid */
            parentId?: string;
            /** Format: int32 */
            index?: number;
        };
        BlockOperation: {
            /** @enum {string} */
            type: "ADD_BLOCK" | "REMOVE_BLOCK" | "MOVE_BLOCK" | "UPDATE_BLOCK" | "REORDER_BLOCK";
            /** Format: uuid */
            blockId: string;
        };
        MoveBlockOperation: WithRequired<components["schemas"]["BlockOperation"], "blockId" | "type"> & {
            /** Format: uuid */
            fromParentId?: string;
            /** Format: uuid */
            toParentId?: string;
        };
        RemoveBlockOperation: WithRequired<components["schemas"]["BlockOperation"], "blockId" | "type"> & {
            childrenIds: {
                [key: string]: string;
            };
            /** Format: uuid */
            parentId?: string;
        };
        ReorderBlockOperation: WithRequired<components["schemas"]["BlockOperation"], "blockId" | "type"> & {
            /** Format: uuid */
            parentId: string;
            /** Format: int32 */
            fromIndex: number;
            /** Format: int32 */
            toIndex: number;
        };
        SaveEnvironmentRequest: {
            /** Format: uuid */
            layoutId: string;
            /** Format: uuid */
            organisationId: string;
            layout: components["schemas"]["TreeLayout"];
            /** Format: int32 */
            version: number;
            operations: components["schemas"]["StructuralOperationRequest"][];
        };
        StructuralOperationRequest: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            timestamp: string;
            data: components["schemas"]["AddBlockOperation"] | components["schemas"]["MoveBlockOperation"] | components["schemas"]["RemoveBlockOperation"] | components["schemas"]["ReorderBlockOperation"] | components["schemas"]["UpdateBlockOperation"];
        };
        UpdateBlockOperation: WithRequired<components["schemas"]["BlockOperation"], "blockId" | "type"> & {
            updatedContent: components["schemas"]["ContentNode"] | components["schemas"]["ReferenceNode"];
        };
        SaveEnvironmentResponse: {
            success: boolean;
            error?: string;
            /** Format: int32 */
            newVersion?: number;
            conflict: boolean;
            /** Format: int32 */
            latestVersion?: number;
            lastModifiedBy?: string;
            /** Format: date-time */
            lastModifiedAt?: string;
            idMappings: {
                [key: string]: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
        };
    };
    updateUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["User"];
            };
        };
        responses: {
            /** @description User profile updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
            /** @description User ID in request does not match session user */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
        };
    };
    updateMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisationId: string;
                role: "OWNER" | "ADMIN" | "MEMBER";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganisationMember"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganisationMember"];
                };
            };
        };
    };
    updateOrganisation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Organisation"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Organisation"];
                };
            };
        };
    };
    createOrganisation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganisationCreationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Organisation"];
                };
            };
        };
    };
    getLineItemById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lineItemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Line item retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LineItem"];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LineItem"];
                };
            };
            /** @description Line item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LineItem"];
                };
            };
        };
    };
    updateLineItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lineItemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineItem"];
            };
        };
        responses: {
            /** @description Line item updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LineItem"];
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LineItem"];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LineItem"];
                };
            };
            /** @description User does not own the line item */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LineItem"];
                };
            };
            /** @description Line item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LineItem"];
                };
            };
        };
    };
    deleteLineItemById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lineItemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Line item deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User does not own the line item */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Line item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getInvoiceById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invoice retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Invoice"];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Invoice"];
                };
            };
            /** @description User does not own the invoice */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Invoice"];
                };
            };
            /** @description Invoice not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Invoice"];
                };
            };
        };
    };
    updateInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Invoice"];
            };
        };
        responses: {
            /** @description Invoice updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Invoice"];
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Invoice"];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Invoice"];
                };
            };
            /** @description User does not own the invoice */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Invoice"];
                };
            };
            /** @description Invoice not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Invoice"];
                };
            };
        };
    };
    deleteInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Invoice"];
            };
        };
        responses: {
            /** @description Invoice deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cannot delete a paid or cancelled invoice */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User does not own the invoice */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invoice not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getClientById: {
        parameters: {
            query?: {
                includeMetadata?: boolean;
            };
            header?: never;
            path: {
                clientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Client retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Client"];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Client"];
                };
            };
            /** @description Client not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Client"];
                };
            };
        };
    };
    updateClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Client"];
            };
        };
        responses: {
            /** @description Client updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Client"];
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Client"];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Client"];
                };
            };
            /** @description User does not own the client */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Client"];
                };
            };
            /** @description Client not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Client"];
                };
            };
        };
    };
    deleteClientById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Client deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User does not own the client */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateArchiveStatusByClientId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: string;
                status: boolean;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Client archival status updated successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User does not own the client */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateBlockType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blockTypeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlockType"];
            };
        };
        responses: {
            /** @description Block type updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Block type not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateArchiveStatusByBlockTypeId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blockTypeId: string;
                status: boolean;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Block type archived successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Block type not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rejectInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inviteToken: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    inviteToOrganisation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisationId: string;
                email: string;
                role: "OWNER" | "ADMIN" | "MEMBER";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganisationInvite"];
                };
            };
        };
    };
    acceptInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inviteToken: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createLineItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineItemCreationRequest"];
            };
        };
        responses: {
            /** @description Line item created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LineItem"];
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LineItem"];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LineItem"];
                };
            };
        };
    };
    cancelInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Invoice"];
            };
        };
        responses: {
            /** @description Invoice cancelled successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Invoice"];
                };
            };
            /** @description Cannot cancel a paid or already cancelled invoice */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Invoice"];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Invoice"];
                };
            };
            /** @description User does not own the invoice */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Invoice"];
                };
            };
            /** @description Invoice not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Invoice"];
                };
            };
        };
    };
    getUserInvoices: {
        parameters: {
            query: {
                organisationId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of invoices retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Invoice"][];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Invoice"][];
                };
            };
        };
    };
    createInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceCreationRequest"];
            };
        };
        responses: {
            /** @description Invoice created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Invoice"];
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Invoice"];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Invoice"];
                };
            };
        };
    };
    createClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientCreationRequest"];
            };
        };
        responses: {
            /** @description Client created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Client"];
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Client"];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Client"];
                };
            };
        };
    };
    publishBlockType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBlockTypeRequest"];
            };
        };
        responses: {
            /** @description Block type created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlockType"];
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlockType"];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlockType"];
                };
            };
        };
    };
    overwriteBlockEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverwriteEnvironmentRequest"];
            };
        };
        responses: {
            /** @description Environment overwritten successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OverwriteEnvironmentResponse"];
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OverwriteEnvironmentResponse"];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OverwriteEnvironmentResponse"];
                };
            };
        };
    };
    saveBlockEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveEnvironmentRequest"];
            };
        };
        responses: {
            /** @description Environment saved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SaveEnvironmentResponse"];
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SaveEnvironmentResponse"];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SaveEnvironmentResponse"];
                };
            };
            /** @description Conflict in versioning when saving environment */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SaveEnvironmentResponse"];
                };
            };
        };
    };
    getUserById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
            /** @description User does not have permission to access this profile */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
        };
    };
    deleteUserProfileById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User does not have permission to delete this profile */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getOrganisation: {
        parameters: {
            query?: {
                includeMetadata?: boolean;
            };
            header?: never;
            path: {
                organisationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Organisation"];
                };
            };
        };
    };
    deleteOrganisation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getUserInvites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganisationInvite"][];
                };
            };
        };
    };
    getOrganisationInvites: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganisationInvite"][];
                };
            };
        };
    };
    getLineItemsForOrganisation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of line items retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LineItem"][];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LineItem"][];
                };
            };
        };
    };
    generateInvoiceDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document generated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description User does not own the invoice */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description Invoice not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    getClientInvoices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Client"];
            };
        };
        responses: {
            /** @description List of invoices retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Invoice"][];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Invoice"][];
                };
            };
            /** @description User does not have access to the client */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Invoice"][];
                };
            };
        };
    };
    getOrganisationClients: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of clients retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Client"][];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Client"][];
                };
            };
            /** @description No clients found for the organisation */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Client"][];
                };
            };
        };
    };
    getBlockTypes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Block types retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlockType"][];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlockType"][];
                };
            };
            /** @description No block types found for the organisation */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlockType"][];
                };
            };
        };
    };
    getBlockTypeByKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Block type retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlockType"];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlockType"];
                };
            };
            /** @description Block type not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlockType"];
                };
            };
        };
    };
    getBlockEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisationId: string;
                type: "line_item" | "client" | "company" | "invoice" | "block_tree" | "report" | "document" | "project" | "organisation" | "task" | "block_type" | "block" | "user";
                entityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Environment retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlockEnvironment"];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlockEnvironment"];
                };
            };
            /** @description Forbidden - insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlockEnvironment"];
                };
            };
            /** @description Entity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlockEnvironment"];
                };
            };
        };
    };
    removeMemberFromOrganisation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganisationMember"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revokeInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisationId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
